version: '3.8'

networks:
  default:
    driver: bridge
services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=tweeter-db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: cache
    image: redis
    ports:
      - 6380:6379
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local
